Use Group9
/*
drop table profile
drop table diet
drop table dataEntry
drop table sleep
drop table trackables
drop table weight
drop table workout
*/
/*
create table profile(
profileID int IDENTITY(1,1),
profileName nvarchar(30),
profilePassword nvarchar(30),
birthDate date,
height int,
weight int,
gender nvarchar(1),
primary key (profileID)
);

create table trackables(
FK_profileID int,
sleepHours decimal(5,2),
workoutDays int,
targetWeight decimal(5,2),
trackDiet bit,

foreign key (FK_profileID) references profile(profileID)
);

create table dataEntry(
dataEntryID int IDENTITY(1,1),
FK_profileID int,
entryYear int,
entryMonth int,
entryWeek int,
entryDay int,

primary key (dataEntryID),
foreign key (FK_profileID) references profile(profileID)
);

create table weight(
FK_dataEntryID ,
currentWeight int,
foreign key (FK_dataEntryID) references dataEntry(dataEntryID)
);

create table workout(
FK_dataEntryID int,
hadInjury bit,
hadWorkout bit,
foreign key (FK_dataEntryID) references dataEntry(dataEntryID)
);

create table sleep(
FK_dataEntryID int,
sleepHours decimal(5,2),
sleepQuality int,
foreign key (FK_dataEntryID) references dataEntry(dataEntryID)
);

create table diet(
FK_dataEntryID int,
waterGlasses int,
hadAlcohol bit,
hadSoda bit,
hadCaffeine bit,
hadCigarettes bit,
hadJunkFood bit,

foreign key (FK_dataEntryID) references dataEntry(dataEntryID)
);
*/
/*
insert into profile (profileName, profilePassword, birthDate, height, weight, gender)
values ('Amanda', 'YasYumYum', '1990-06-09', 164, 59, 'f');

insert into profile (profileName, profilePassword, birthDate, height, weight, gender)
values ('Bryson', 'DuffNBuff', '1995-02-19', 174, 70, 'm');

insert into profile (profileName, profilePassword, birthDate, height, weight, gender)
values ('Anjelica', 'Password', '1994-02-19', 170, 65, 'f');

insert into profile (profileName, profilePassword, birthDate, height, weight, gender)
values ('Synthia', '12345678', '1984-03-19', 160, 56, 'f');

insert into profile (profileName, profilePassword, birthDate, height, weight, gender)
values ('Noel', 'fabreez', '1984-08-22', 185, 95, 'm');
*/
/*
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 6, 26, 29)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 6, 26, 30)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 26, 1)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 27, 2)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 27, 3)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 27, 4)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 27, 5)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 27, 6)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 27, 7)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 27, 8)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 28, 9)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 28, 10)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 28, 11)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 28, 12)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 28, 13)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 28, 14)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 28, 15)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 29, 16)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 29, 17)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 29, 18)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 29, 19)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 29, 20)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 29, 21)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 29, 22)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 30, 23)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 30, 24)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 30, 25)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 30, 26)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 30, 27)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 30, 28)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 30, 29)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 31, 30)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 7, 31, 31)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 31, 1)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 31, 2)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 31, 3)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 31, 4)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 31, 5)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 32, 6)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 32, 7)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 32, 8)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 32, 9)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 32, 10)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 32, 11)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 32, 12)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 33, 13)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 33, 14)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 33, 15)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 33, 16)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 33, 17)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 33, 18)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 33, 19)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 34, 20)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 34, 21)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 34, 22)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 34, 23)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 34, 24)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 34, 25)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 34, 26)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 35, 27)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 35, 28)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 35, 29)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 35, 30)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 35, 31)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 35, 1)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 35, 2)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 36, 3)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 36, 4)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 36, 5)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 36, 6)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 36, 7)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 36, 8)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 36, 9)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 37, 10)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 37, 11)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 37, 12)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 37, 13)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 37, 14)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 37, 15)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 37, 16)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 38, 17)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 38, 18)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 38, 19)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 38, 20)
insert into dataEntry(FK_profileID, entryYear, entryMonth, entryWeek, entryDay)
values(5, 2018, 8, 38, 21)
*/

/*
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(1, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(2, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(3, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(4, 5, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(5, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(6, 7, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(7, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(8, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(9, 3, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(10, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(11, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(12, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(13, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(14, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(15, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(16, 9, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(17, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(18, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(19, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(20, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(21, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(22, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(23, 4, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(24, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(25, 5, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(26, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(27, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(28, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(29, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(30, 5, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(31, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(32, 7, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(33, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(34, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(35, 3, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(36, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(37, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(38, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(39, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(40, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(41, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(42, 9, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(43, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(44, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(45, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(46, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(47, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(48, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(49, 4, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(50, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(51, 5, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(52, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(53, 3, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(54, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(55, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(56, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(57, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(58, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(59, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(60, 9, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(61, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(62, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(63, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(64, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(65, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(66, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(67, 4, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(68, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(69, 5, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(70, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(71, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(72, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(73, 4, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(74, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(75, 2, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(76, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(77, 4, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(78, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(79, 5, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(80, 6, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(81, 6, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(82, 4, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(83, 5, 0, 0, 1, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(84, 5, 0, 0, 0, 0, 0)
insert into diet(FK_dataEntryID, waterGlasses, hadAlcohol, hadSoda, hadCaffeine, hadCigarettes, hadJunkFood)
values(85, 6, 0, 0, 0, 0, 0)
*/
/*
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(1, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(2, 7, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(3, 6, 1)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(4, 8.5, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(5, 8.2, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(6, 8, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(7, 7.5, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(8, 6, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(9, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(10, 7, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(11, 7.2, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(12, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(13, 6.8, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(14, 5, 1)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(15, 6.3, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(16, 7.5, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(17, 8, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(18, 9, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(19, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(20, 6.3, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(21, 7, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(22, 7, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(23, 6.3, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(24, 6.4, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(25, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(26, 7, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(27, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(28, 8.2, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(29, 10, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(30, 4, 1)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(31, 7.5, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(32, 6, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(33, 6.5, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(34, 6.7, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(35, 7, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(36, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(37, 6.9, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(38, 6, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(39, 5.4, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(40, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(41, 7, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(42, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(43, 7.1, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(44, 7, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(45, 7, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(46, 7.5, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(47, 6, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(48, 4.9, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(49, 5.7, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(50, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(51, 7, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(52, 5, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(53, 4, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(54, 7, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(55, 4, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(56, 7, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(57, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(58, 7.2, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(59, 6.4, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(60, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(61, 8.6, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(62, 8, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(63, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(64, 5.2, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(65, 5.4, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(66, 6.1, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(67, 6.2, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(68, 6.8, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(69, 8.8, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(70, 7.5, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(71, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(72, 7.3, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(73, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(74, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(75, 7, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(76, 7, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(77, 7.5, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(78, 7.4, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(79, 6, 2)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(80, 6.5, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(81, 6.3, 3)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(82, 6.1, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(83, 6.4, 5)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(84, 6.9, 4)
insert into sleep(FK_dataEntryID, sleepHours, sleepQuality)
values(85, 7.5, 4)
*/
/*
drop table trackables
create table trackables(
FK_profileID int,
sleepHours decimal(5,2),
workoutDays int,
targetWeight decimal(5,2),
trackDiet bit,

foreign key (FK_profileID) references profile(profileID)
);
*/
/*
drop table weight
create table weight(
FK_dataEntryID int,
currentWeight decimal(5,2),

foreign key (FK_dataEntryID) references dataEntry(dataEntryID)
);
*/
/*
insert into weight(FK_dataEntryID, currentWeight)
values(1, 95.2)
insert into weight(FK_dataEntryID, currentWeight)
values(2, 95)
insert into weight(FK_dataEntryID, currentWeight)
values(3, 94.6)
insert into weight(FK_dataEntryID, currentWeight)
values(4, 94.4)
insert into weight(FK_dataEntryID, currentWeight)
values(5, 94.2)
insert into weight(FK_dataEntryID, currentWeight)
values(6, 94.2)
insert into weight(FK_dataEntryID, currentWeight)
values(7, 93.3)
insert into weight(FK_dataEntryID, currentWeight)
values(8, 93.9)
insert into weight(FK_dataEntryID, currentWeight)
values(9, 94.2)
insert into weight(FK_dataEntryID, currentWeight)
values(10, 93.1)
insert into weight(FK_dataEntryID, currentWeight)
values(11, 93.2)
insert into weight(FK_dataEntryID, currentWeight)
values(12, 92.5)
insert into weight(FK_dataEntryID, currentWeight)
values(13, 92.2)
insert into weight(FK_dataEntryID, currentWeight)
values(14, 91.9)
insert into weight(FK_dataEntryID, currentWeight)
values(15, 92.6)
insert into weight(FK_dataEntryID, currentWeight)
values(16, 91.8)
insert into weight(FK_dataEntryID, currentWeight)
values(17, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(18, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(19, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(20, 91.0)
insert into weight(FK_dataEntryID, currentWeight)
values(21, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(22, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(23, 90.3)
insert into weight(FK_dataEntryID, currentWeight)
values(24, 90.8)
insert into weight(FK_dataEntryID, currentWeight)
values(25, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(26, 89.9)
insert into weight(FK_dataEntryID, currentWeight)
values(27, 89.8)
insert into weight(FK_dataEntryID, currentWeight)
values(28, 89.4)
insert into weight(FK_dataEntryID, currentWeight)
values(29, 89.2)
insert into weight(FK_dataEntryID, currentWeight)
values(30, 90.1)
insert into weight(FK_dataEntryID, currentWeight)
values(31, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(32, 90.5)
insert into weight(FK_dataEntryID, currentWeight)
values(33, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(34, 91.9)
insert into weight(FK_dataEntryID, currentWeight)
values(35, 91.6)
insert into weight(FK_dataEntryID, currentWeight)
values(36, 91.8)
insert into weight(FK_dataEntryID, currentWeight)
values(37, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(38, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(39, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(40, 90.1)
insert into weight(FK_dataEntryID, currentWeight)
values(41, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(42, 90.5)
insert into weight(FK_dataEntryID, currentWeight)
values(43, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(44, 90.9)
insert into weight(FK_dataEntryID, currentWeight)
values(45, 90.6)
insert into weight(FK_dataEntryID, currentWeight)
values(46, 90.8)
insert into weight(FK_dataEntryID, currentWeight)
values(47, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(48, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(49, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(50, 90.1)
insert into weight(FK_dataEntryID, currentWeight)
values(51, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(52, 90.5)
insert into weight(FK_dataEntryID, currentWeight)
values(53, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(54, 90.9)
insert into weight(FK_dataEntryID, currentWeight)
values(55, 90.6)
insert into weight(FK_dataEntryID, currentWeight)
values(56, 90.8)
insert into weight(FK_dataEntryID, currentWeight)
values(57, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(58, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(59, 91.2)
insert into weight(FK_dataEntryID, currentWeight)
values(60, 90.1)
insert into weight(FK_dataEntryID, currentWeight)
values(61, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(62, 90.5)
insert into weight(FK_dataEntryID, currentWeight)
values(63, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(64, 90.9)
insert into weight(FK_dataEntryID, currentWeight)
values(65, 90.6)
insert into weight(FK_dataEntryID, currentWeight)
values(66, 90.8)
insert into weight(FK_dataEntryID, currentWeight)
values(67, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(68, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(69, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(70, 90.1)
insert into weight(FK_dataEntryID, currentWeight)
values(71, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(72, 90.5)
insert into weight(FK_dataEntryID, currentWeight)
values(73, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(74, 90.9)
insert into weight(FK_dataEntryID, currentWeight)
values(75, 90.6)
insert into weight(FK_dataEntryID, currentWeight)
values(76, 90.8)
insert into weight(FK_dataEntryID, currentWeight)
values(77, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(78, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(79, 90.2)
insert into weight(FK_dataEntryID, currentWeight)
values(80, 89.8)
insert into weight(FK_dataEntryID, currentWeight)
values(81, 89.2)
insert into weight(FK_dataEntryID, currentWeight)
values(82, 88.2)
insert into weight(FK_dataEntryID, currentWeight)
values(83, 87.8)
insert into weight(FK_dataEntryID, currentWeight)
values(84, 88.0)
insert into weight(FK_dataEntryID, currentWeight)
values(85, 88.5)
*/

insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(1, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(2, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(3, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(4, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(5, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(6, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(7, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(8, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(9, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(10, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(11, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(12, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(13, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(14, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(15, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(16, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(17, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(18, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(19, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(20, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(21, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(22, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(23, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(24, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(25, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(26, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(27, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(28, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(29, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(30, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(31, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(32, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(33, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(34, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(35, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(36, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(37, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(38, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(39, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(40, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(41, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(42, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(43, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(44, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(45, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(46, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(47, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(48, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(49, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(50, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(51, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(52, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(53, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(54, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(55, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(56, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(57, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(58, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(59, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(60, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(61, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(62, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(63, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(64, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(65, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(66, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(67, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(68, 1, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(69, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(70, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(71, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(72, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(73, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(74, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(75, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(76, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(77, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(78, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(79, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(80, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(81, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(82, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(83, 0, 1)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(84, 0, 0)
insert into workout(FK_dataEntryID, hadInjury, hadWorkout)
values(85, 0, 1)

/*
drop table workout
create table workout(
FK_dataEntryID int,
hadInjury bit,
hadWorkout bit,
foreign key (FK_dataEntryID) references dataEntry(dataEntryID)
);
*/
select * from workout
